# Generated by Django 5.1.3 on 2024-12-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food & Dining', 'Food & Dining'), ('Transport', 'Transport'), ('Accommodation', 'Accommodation'), ('Entertainment', 'Entertainment'), ('Shopping', 'Shopping'), ('Other', 'Other')]),
        ),
        migrations.AlterField(
            model_name='note',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Packing', 'Packing'), ('Reminder', 'Reminder'), ('Feedback', 'Feedback')]),
        ),
    ]
