# Generated by Django 5.1.3 on 2024-12-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('Sightseeing', 'Sightseeing'), ('Dining', 'Dining'), ('Adventure', 'Adventure'), ('Relaxation', 'Relaxation'), ('Shopping', 'Shopping')]),
        ),
    ]
